// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5TU8r8N_0UM79DQrLcvVhfdbwoVceeY',
    appId: '1:466645973956:web:60c794955eb29990094291',
    messagingSenderId: '466645973956',
    projectId: 'tourista-74c8b',
    authDomain: 'tourista-74c8b.firebaseapp.com',
    storageBucket: 'tourista-74c8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHCCNxctPuovRmVAJC0MjX03d1nM1DNvk',
    appId: '1:466645973956:android:541a49949772fe7d094291',
    messagingSenderId: '466645973956',
    projectId: 'tourista-74c8b',
    storageBucket: 'tourista-74c8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6YeLAIEjOZOdh948rYNzq0KkRN6wRSJc',
    appId: '1:466645973956:ios:f5349bfedb970f77094291',
    messagingSenderId: '466645973956',
    projectId: 'tourista-74c8b',
    storageBucket: 'tourista-74c8b.appspot.com',
    iosBundleId: 'com.example.tourista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6YeLAIEjOZOdh948rYNzq0KkRN6wRSJc',
    appId: '1:466645973956:ios:f5349bfedb970f77094291',
    messagingSenderId: '466645973956',
    projectId: 'tourista-74c8b',
    storageBucket: 'tourista-74c8b.appspot.com',
    iosBundleId: 'com.example.tourista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW5TU8r8N_0UM79DQrLcvVhfdbwoVceeY',
    appId: '1:466645973956:web:61567f73518169cd094291',
    messagingSenderId: '466645973956',
    projectId: 'tourista-74c8b',
    authDomain: 'tourista-74c8b.firebaseapp.com',
    storageBucket: 'tourista-74c8b.appspot.com',
  );
}
